//! Golden reference file formats for a DC operating point ([`GoldenDc`], § ladder rungs 1/5) and
//! a `.dc` sweep ([`GoldenSweep`], § ladder rung 2). A transient waveform isn't wired to golden
//! yet — see `docs/roadmap.md`'s T6.3 notes.
//!
//! A `.golden` file (one operating point) is plain text: one `<node> <value>` pair per line, in
//! the circuit's own `node_order` (so a byte diff against a regenerated file reads as a real
//! circuit change, not reordering noise). Blank lines and `#`-prefixed comment lines are
//! ignored.
//!
//! ```text
//! # golden/divider.golden — generated by `cargo xtask gen-golden`
//! in 1
//! mid 0.5
//! ```
//!
//! A sweep golden file is a small table: a header line naming the swept source and every node,
//! then one row per swept point (`<swept value> <node value> ...`, in the same node order the
//! header declared).
//!
//! ```text
//! # golden/diode_iv.golden — generated by `cargo xtask gen-golden`
//! V1 in
//! 0 0
//! 0.1 0.1
//! ```

use crate::HarnessError;

/// One committed golden reference: a DC operating point's node voltages, in `node_order`.
#[derive(Clone, Debug, PartialEq)]
pub struct GoldenDc {
    /// Node names, in the same order as [`Self::values`].
    pub node_order: Vec<String>,
    /// Node voltages, one per `node_order` entry.
    pub values: Vec<f64>,
}

impl GoldenDc {
    /// Build from a solved circuit's node names and full unknown vector — only the leading
    /// `node_order.len()` entries of `x` are node voltages (branch-current/internal unknowns,
    /// if any, follow them — see `va-cli::build_instances`'s doc comment), so this only ever
    /// reads that prefix.
    pub fn from_operating_point(node_order: &[String], x: &[f64]) -> Self {
        Self {
            node_order: node_order.to_vec(),
            values: x[..node_order.len()].to_vec(),
        }
    }

    /// Parse a `.golden` file's text (this module's doc comment shows the format).
    ///
    /// # Errors
    ///
    /// [`HarnessError::Golden`] on a line that isn't blank/a comment/`<node> <value>`.
    pub fn parse(text: &str) -> Result<Self, HarnessError> {
        let mut node_order = Vec::new();
        let mut values = Vec::new();
        for (i, raw) in text.lines().enumerate() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let golden_err = |message: &str| HarnessError::Golden {
                line: i + 1,
                message: message.to_string(),
            };
            let mut parts = line.split_whitespace();
            let name = parts
                .next()
                .ok_or_else(|| golden_err("expected `<node> <value>`"))?;
            let value: f64 = parts
                .next()
                .ok_or_else(|| golden_err("missing value"))?
                .parse()
                .map_err(|_| golden_err("unparseable value"))?;
            if parts.next().is_some() {
                return Err(golden_err(
                    "expected exactly `<node> <value>`, found extra tokens",
                ));
            }
            node_order.push(name.to_string());
            values.push(value);
        }
        Ok(Self { node_order, values })
    }

    /// Read a `.golden` file from disk.
    ///
    /// # Errors
    ///
    /// [`HarnessError::MissingGolden`] if `path` doesn't exist/can't be read;
    /// [`HarnessError::Golden`] if its contents don't parse.
    pub fn read(path: &std::path::Path) -> Result<Self, HarnessError> {
        let text = std::fs::read_to_string(path)
            .map_err(|_| HarnessError::MissingGolden(path.display().to_string()))?;
        Self::parse(&text)
    }

    /// Render as `.golden` text — round-trips exactly through [`Self::parse`], since `f64`'s
    /// `Display` is Rust's shortest-round-trippable-decimal formatting, not a truncated one.
    pub fn render(&self) -> String {
        let mut out = String::new();
        for (name, value) in self.node_order.iter().zip(&self.values) {
            out.push_str(&format!("{name} {value}\n"));
        }
        out
    }
}

/// One committed golden reference for a `.dc` sweep (§ ladder rung 2): every swept value's own
/// node voltages, in sweep order. Unlike [`GoldenDc`], every point necessarily shares one
/// `node_order` (the same circuit, just a different source value each time), so it's hoisted
/// out of the per-point records instead of repeated.
#[derive(Clone, Debug, PartialEq)]
pub struct GoldenSweep {
    /// The swept source's name (`va_netlist::DcSweep::source`).
    pub source: String,
    /// Node names, in the same order as each point's voltages.
    pub node_order: Vec<String>,
    /// `(swept value, node voltages in `node_order`)`, in sweep order.
    pub points: Vec<(f64, Vec<f64>)>,
}

impl GoldenSweep {
    /// Build from a solved sweep's swept-source name, node names, and per-point results.
    pub fn from_sweep(source: &str, node_order: &[String], points: &[(f64, Vec<f64>)]) -> Self {
        Self {
            source: source.to_string(),
            node_order: node_order.to_vec(),
            points: points.to_vec(),
        }
    }

    /// Parse a sweep `.golden` file's text (this module's doc comment shows the format): a
    /// header line (`<source> <node> ...`), then one `<value> <node value> ...` row per point.
    ///
    /// # Errors
    ///
    /// [`HarnessError::Golden`] on a missing/malformed header, or a row whose value count
    /// doesn't match the header's node count.
    pub fn parse(text: &str) -> Result<Self, HarnessError> {
        let golden_err = |line: usize, message: &str| HarnessError::Golden {
            line,
            message: message.to_string(),
        };
        let mut real_lines = text
            .lines()
            .enumerate()
            .filter(|(_, raw)| {
                let t = raw.trim();
                !t.is_empty() && !t.starts_with('#')
            })
            .map(|(i, raw)| (i + 1, raw));

        let (header_line, header) = real_lines
            .next()
            .ok_or_else(|| golden_err(1, "empty sweep golden file (expected a header line)"))?;
        let mut header_toks = header.split_whitespace();
        let source = header_toks
            .next()
            .ok_or_else(|| golden_err(header_line, "missing swept source name in header"))?
            .to_string();
        let node_order: Vec<String> = header_toks.map(str::to_string).collect();
        if node_order.is_empty() {
            return Err(golden_err(header_line, "header names no nodes"));
        }

        let mut points = Vec::new();
        for (line, raw) in real_lines {
            let toks: Vec<f64> = raw
                .split_whitespace()
                .map(|t| t.parse().map_err(|_| golden_err(line, "unparseable value")))
                .collect::<Result<_, _>>()?;
            if toks.len() != node_order.len() + 1 {
                return Err(golden_err(
                    line,
                    &format!(
                        "expected {} value(s) (1 swept + {} node), found {}",
                        node_order.len() + 1,
                        node_order.len(),
                        toks.len()
                    ),
                ));
            }
            points.push((toks[0], toks[1..].to_vec()));
        }
        Ok(Self {
            source,
            node_order,
            points,
        })
    }

    /// Read a sweep `.golden` file from disk.
    ///
    /// # Errors
    ///
    /// [`HarnessError::MissingGolden`] if `path` doesn't exist/can't be read;
    /// [`HarnessError::Golden`] if its contents don't parse.
    pub fn read(path: &std::path::Path) -> Result<Self, HarnessError> {
        let text = std::fs::read_to_string(path)
            .map_err(|_| HarnessError::MissingGolden(path.display().to_string()))?;
        Self::parse(&text)
    }

    /// Render as sweep `.golden` text — round-trips exactly through [`Self::parse`].
    pub fn render(&self) -> String {
        let mut out = format!("{} {}\n", self.source, self.node_order.join(" "));
        for (value, values) in &self.points {
            out.push_str(&value.to_string());
            for v in values {
                out.push(' ');
                out.push_str(&v.to_string());
            }
            out.push('\n');
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_ignores_comments_and_blank_lines() {
        let g = GoldenDc::parse("# a comment\n\nin 1\nmid 0.5\n").unwrap();
        assert_eq!(g.node_order, vec!["in", "mid"]);
        assert_eq!(g.values, vec![1.0, 0.5]);
    }

    #[test]
    fn render_round_trips_through_parse() {
        let g = GoldenDc {
            node_order: vec!["in".to_string(), "mid".to_string()],
            values: vec![1.0, 0.123456789012345],
        };
        let text = g.render();
        let parsed = GoldenDc::parse(&text).unwrap();
        assert_eq!(g, parsed);
    }

    #[test]
    fn missing_value_is_an_error() {
        assert!(GoldenDc::parse("in\n").is_err());
    }

    #[test]
    fn unparseable_value_is_an_error() {
        assert!(GoldenDc::parse("in notanumber\n").is_err());
    }

    #[test]
    fn extra_tokens_are_an_error() {
        assert!(GoldenDc::parse("in 1 extra\n").is_err());
    }

    #[test]
    fn from_operating_point_drops_trailing_branch_unknowns() {
        // `x` carries a source's own branch-current unknown after the node voltages.
        let node_order = vec!["in".to_string(), "mid".to_string()];
        let x = [1.0, 0.5, -0.001];
        let g = GoldenDc::from_operating_point(&node_order, &x);
        assert_eq!(g.values, vec![1.0, 0.5]);
    }

    #[test]
    fn sweep_parse_reads_header_and_rows() {
        let g = GoldenSweep::parse("# a comment\nV1 in\n0 0\n0.1 0.1\n").unwrap();
        assert_eq!(g.source, "V1");
        assert_eq!(g.node_order, vec!["in"]);
        assert_eq!(g.points, vec![(0.0, vec![0.0]), (0.1, vec![0.1])]);
    }

    #[test]
    fn sweep_render_round_trips_through_parse() {
        let g = GoldenSweep {
            source: "V1".to_string(),
            node_order: vec!["in".to_string()],
            points: vec![(0.0, vec![0.0]), (0.3, vec![-1.095908e-9])],
        };
        let text = g.render();
        let parsed = GoldenSweep::parse(&text).unwrap();
        assert_eq!(g, parsed);
    }

    #[test]
    fn sweep_empty_file_is_an_error() {
        assert!(GoldenSweep::parse("").is_err());
        assert!(GoldenSweep::parse("# only a comment\n").is_err());
    }

    #[test]
    fn sweep_row_with_wrong_value_count_is_an_error() {
        // Header declares one node ("in"), so each row needs exactly 2 values (swept + in).
        assert!(GoldenSweep::parse("V1 in\n0 0 1\n").is_err());
        assert!(GoldenSweep::parse("V1 in\n0\n").is_err());
    }

    #[test]
    fn sweep_from_sweep_matches_manual_construction() {
        let g = GoldenSweep::from_sweep(
            "V1",
            &["in".to_string()],
            &[(0.0, vec![0.0]), (0.1, vec![0.1])],
        );
        assert_eq!(g.source, "V1");
        assert_eq!(g.node_order, vec!["in"]);
        assert_eq!(g.points, vec![(0.0, vec![0.0]), (0.1, vec![0.1])]);
    }
}
