//! Golden reference file formats for a DC operating point ([`GoldenDc`], § ladder rungs 1/5), a
//! `.dc` sweep ([`GoldenSweep`], § ladder rung 2), a `.tran` transient run ([`GoldenTran`],
//! § ladder rungs 3/4/6), an `.ac` small-signal sweep ([`GoldenAc`], T5), and a `.noise` sweep
//! ([`GoldenNoise`], T5.2).
//!
//! A `.golden` file (one operating point) is plain text: one `<node> <value>` pair per line, in
//! the circuit's own `node_order` (so a byte diff against a regenerated file reads as a real
//! circuit change, not reordering noise). Blank lines and `#`-prefixed comment lines are
//! ignored.
//!
//! ```text
//! # golden/divider.golden — generated by `cargo xtask gen-golden`
//! in 1
//! mid 0.5
//! ```
//!
//! A sweep golden file is a small table: a header line naming the swept source and every node,
//! then one row per swept point (`<swept value> <node value> ...`, in the same node order the
//! header declared).
//!
//! ```text
//! # golden/diode_iv.golden — generated by `cargo xtask gen-golden`
//! V1 in
//! 0 0
//! 0.1 0.1
//! ```
//!
//! A transient golden file is the same table shape as a sweep, with a leading `@tran` marker in
//! place of a swept source's name — the independent variable is always time, not a device
//! parameter, so there is nothing to name — then one row per sampled time (`<time> <node
//! value> ...`). The two runs being compared almost never share a timebase (two different
//! adaptive-timestep integrators; see [`crate::metrics::resample_linear`]), so [`GoldenTran`]'s
//! own comparison path resamples onto the golden's times rather than assuming row-for-row
//! alignment the way [`GoldenSweep`]'s does.
//!
//! ```text
//! # golden/rc_step.golden — generated by `cargo xtask gen-golden`
//! @tran out
//! 0 0
//! 2e-5 0.0995
//! ```
//!
//! An AC golden file ([`GoldenAc`], T5) is again the same table shape, with an `@ac` header
//! marker and frequency as the independent variable — but **two** columns per name, the real and
//! imaginary parts of that complex response, since a small-signal result is a complex number
//! rather than a real one. Storing re/im rather than magnitude/phase keeps the file a lossless
//! record of what the simulator produced; [`crate::ac::compare_ac`] derives magnitude and phase
//! from it at comparison time (§7's AC metric is stated in those terms).
//!
//! ```text
//! # golden/rc_ac.golden — generated by `cargo xtask gen-golden`
//! @ac out I(V1)
//! 1 0.999961 -0.00628294 -3.94769e-08 -6.28294e-06
//! ```
//!
//! A noise golden file ([`GoldenNoise`], T5.2) has a `@noise <output> <source>` header naming
//! both the probed node and the input source the noise is referred back to, then one
//! `<frequency> <output psd> <input-referred psd>` row per point. Both columns are V²/Hz: the
//! total output PSD summed over every contributing device, and that same noise divided by the
//! squared forward gain from `<source>` (this project keeps no per-device breakdown; §
//! `va_acnoise::noise`'s own limitations).
//!
//! ```text
//! # golden/diode_noise.golden — generated by `cargo xtask gen-golden`
//! @noise a V1
//! 10 1.98771e-18 4.97535e-17
//! ```
//!
//! **`node_order` may also carry named branch currents, not just node voltages** — a
//! `vsource` device's own current is a real, directly-solved MNA unknown (§
//! `va-cli::branch_currents`), and for a circuit where a device's node voltage is directly
//! forced by a source (e.g. `circuits/diode_iv.net`'s `V1` across `D1`), that forced voltage
//! trivially matches golden regardless of whether the *device* model is right at all — the
//! source's own current is the quantity that actually depends on it. Each constructor
//! (`from_operating_point`/`from_sweep`/`from_waveform`) appends one `I(<device name>)`-labeled
//! entry per branch current after the node entries, in the exact same `<name> <value>` shape —
//! the file format doesn't change, `node_order` just isn't only node names anymore:
//!
//! ```text
//! # golden/divider.golden — generated by `cargo xtask gen-golden`
//! in 1
//! mid 0.5
//! I(V1) -0.0005
//! ```

use crate::HarnessError;

/// Append each `(device name, global index)` in `branch_currents` as an `I(<name>)`-labeled
/// column after `node_order`'s own columns — shared by every golden constructor (this module's
/// own doc comment explains why a branch current belongs in the same named-column list as a
/// node voltage).
fn combined_node_order(node_order: &[String], branch_currents: &[(String, usize)]) -> Vec<String> {
    let mut names = node_order.to_vec();
    names.extend(branch_currents.iter().map(|(name, _)| format!("I({name})")));
    names
}

/// Like [`combined_node_order`], for one solved unknown vector `x`: the leading `node_order_len`
/// entries are node voltages, then one value per `branch_currents` entry, read from `x` at its
/// own recorded global index (not necessarily contiguous with the node prefix — a branch current
/// can sit anywhere past it, depending on what other devices' own internal unknowns interleave).
fn combined_values(
    node_order_len: usize,
    x: &[f64],
    branch_currents: &[(String, usize)],
) -> Vec<f64> {
    let mut values = x[..node_order_len].to_vec();
    values.extend(branch_currents.iter().map(|&(_, idx)| x[idx]));
    values
}

/// One committed golden reference: a DC operating point's node voltages, in `node_order`.
#[derive(Clone, Debug, PartialEq)]
pub struct GoldenDc {
    /// Node names, in the same order as [`Self::values`].
    pub node_order: Vec<String>,
    /// Node voltages, one per `node_order` entry.
    pub values: Vec<f64>,
}

impl GoldenDc {
    /// Build from a solved circuit's node names, full unknown vector, and named branch currents
    /// (§ this module's own doc comment — typically `va-cli::branch_currents`'s own return).
    /// Only the leading `node_order.len()` entries of `x` are node voltages (other
    /// branch-current/internal unknowns, if any, follow them — see `va-cli::build_instances`'s
    /// doc comment); `branch_currents` names which of those extra entries are worth keeping.
    pub fn from_operating_point(
        node_order: &[String],
        x: &[f64],
        branch_currents: &[(String, usize)],
    ) -> Self {
        Self {
            node_order: combined_node_order(node_order, branch_currents),
            values: combined_values(node_order.len(), x, branch_currents),
        }
    }

    /// Parse a `.golden` file's text (this module's doc comment shows the format).
    ///
    /// # Errors
    ///
    /// [`HarnessError::Golden`] on a line that isn't blank/a comment/`<node> <value>`.
    pub fn parse(text: &str) -> Result<Self, HarnessError> {
        let mut node_order = Vec::new();
        let mut values = Vec::new();
        for (i, raw) in text.lines().enumerate() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let golden_err = |message: &str| HarnessError::Golden {
                line: i + 1,
                message: message.to_string(),
            };
            let mut parts = line.split_whitespace();
            let name = parts
                .next()
                .ok_or_else(|| golden_err("expected `<node> <value>`"))?;
            let value: f64 = parts
                .next()
                .ok_or_else(|| golden_err("missing value"))?
                .parse()
                .map_err(|_| golden_err("unparseable value"))?;
            if parts.next().is_some() {
                return Err(golden_err(
                    "expected exactly `<node> <value>`, found extra tokens",
                ));
            }
            node_order.push(name.to_string());
            values.push(value);
        }
        Ok(Self { node_order, values })
    }

    /// Read a `.golden` file from disk.
    ///
    /// # Errors
    ///
    /// [`HarnessError::MissingGolden`] if `path` doesn't exist/can't be read;
    /// [`HarnessError::Golden`] if its contents don't parse.
    pub fn read(path: &std::path::Path) -> Result<Self, HarnessError> {
        let text = std::fs::read_to_string(path)
            .map_err(|_| HarnessError::MissingGolden(path.display().to_string()))?;
        Self::parse(&text)
    }

    /// Render as `.golden` text — round-trips exactly through [`Self::parse`], since `f64`'s
    /// `Display` is Rust's shortest-round-trippable-decimal formatting, not a truncated one.
    pub fn render(&self) -> String {
        let mut out = String::new();
        for (name, value) in self.node_order.iter().zip(&self.values) {
            out.push_str(&format!("{name} {value}\n"));
        }
        out
    }
}

/// One committed golden reference for a `.dc` sweep (§ ladder rung 2): every swept value's own
/// node voltages, in sweep order. Unlike [`GoldenDc`], every point necessarily shares one
/// `node_order` (the same circuit, just a different source value each time), so it's hoisted
/// out of the per-point records instead of repeated.
#[derive(Clone, Debug, PartialEq)]
pub struct GoldenSweep {
    /// The swept source's name (`va_netlist::DcSweep::source`).
    pub source: String,
    /// Node names, in the same order as each point's voltages.
    pub node_order: Vec<String>,
    /// `(swept value, node voltages in `node_order`)`, in sweep order.
    pub points: Vec<(f64, Vec<f64>)>,
}

impl GoldenSweep {
    /// Build from a solved sweep's swept-source name, node names, and per-point results, plus
    /// named branch currents (§ this module's own doc comment). **Contract:** each point's
    /// `Vec<f64>` must be the *full* solved unknown vector, not pre-truncated to node voltages —
    /// this constructor does that truncation itself (mirroring
    /// [`GoldenDc::from_operating_point`]) so it can also reach any branch-current entry past
    /// the node prefix.
    pub fn from_sweep(
        source: &str,
        node_order: &[String],
        points: &[(f64, Vec<f64>)],
        branch_currents: &[(String, usize)],
    ) -> Self {
        Self {
            source: source.to_string(),
            node_order: combined_node_order(node_order, branch_currents),
            points: points
                .iter()
                .map(|(v, x)| (*v, combined_values(node_order.len(), x, branch_currents)))
                .collect(),
        }
    }

    /// Parse a sweep `.golden` file's text (this module's doc comment shows the format): a
    /// header line (`<source> <node> ...`), then one `<value> <node value> ...` row per point.
    ///
    /// # Errors
    ///
    /// [`HarnessError::Golden`] on a missing/malformed header, or a row whose value count
    /// doesn't match the header's node count.
    pub fn parse(text: &str) -> Result<Self, HarnessError> {
        let golden_err = |line: usize, message: &str| HarnessError::Golden {
            line,
            message: message.to_string(),
        };
        let mut real_lines = text
            .lines()
            .enumerate()
            .filter(|(_, raw)| {
                let t = raw.trim();
                !t.is_empty() && !t.starts_with('#')
            })
            .map(|(i, raw)| (i + 1, raw));

        let (header_line, header) = real_lines
            .next()
            .ok_or_else(|| golden_err(1, "empty sweep golden file (expected a header line)"))?;
        let mut header_toks = header.split_whitespace();
        let source = header_toks
            .next()
            .ok_or_else(|| golden_err(header_line, "missing swept source name in header"))?
            .to_string();
        let node_order: Vec<String> = header_toks.map(str::to_string).collect();
        if node_order.is_empty() {
            return Err(golden_err(header_line, "header names no nodes"));
        }

        let mut points = Vec::new();
        for (line, raw) in real_lines {
            let toks: Vec<f64> = raw
                .split_whitespace()
                .map(|t| t.parse().map_err(|_| golden_err(line, "unparseable value")))
                .collect::<Result<_, _>>()?;
            if toks.len() != node_order.len() + 1 {
                return Err(golden_err(
                    line,
                    &format!(
                        "expected {} value(s) (1 swept + {} node), found {}",
                        node_order.len() + 1,
                        node_order.len(),
                        toks.len()
                    ),
                ));
            }
            points.push((toks[0], toks[1..].to_vec()));
        }
        Ok(Self {
            source,
            node_order,
            points,
        })
    }

    /// Read a sweep `.golden` file from disk.
    ///
    /// # Errors
    ///
    /// [`HarnessError::MissingGolden`] if `path` doesn't exist/can't be read;
    /// [`HarnessError::Golden`] if its contents don't parse.
    pub fn read(path: &std::path::Path) -> Result<Self, HarnessError> {
        let text = std::fs::read_to_string(path)
            .map_err(|_| HarnessError::MissingGolden(path.display().to_string()))?;
        Self::parse(&text)
    }

    /// Render as sweep `.golden` text — round-trips exactly through [`Self::parse`].
    pub fn render(&self) -> String {
        let mut out = format!("{} {}\n", self.source, self.node_order.join(" "));
        for (value, values) in &self.points {
            out.push_str(&value.to_string());
            for v in values {
                out.push(' ');
                out.push_str(&v.to_string());
            }
            out.push('\n');
        }
        out
    }
}

/// One committed golden reference for a `.tran` transient run (§ ladder rungs 3/4/6): every
/// sampled time's own node voltages, in time order. Same shape as [`GoldenSweep`] (time in place
/// of a swept source's value) but with no `source` field to name — a transient run's independent
/// variable is always time, never a device parameter — and a `@tran` header marker instead, so a
/// `.golden` file's own text says unambiguously which parser it needs.
#[derive(Clone, Debug, PartialEq)]
pub struct GoldenTran {
    /// Node names, in the same order as each point's voltages.
    pub node_order: Vec<String>,
    /// `(time, node voltages in `node_order`)`, in time order.
    pub points: Vec<(f64, Vec<f64>)>,
}

impl GoldenTran {
    /// Build from a solved transient waveform's node names and full solution-vector rows, plus
    /// named branch currents (§ this module's own doc comment). `x`'s rows are already the full
    /// solved vector (`va_transient::integrator::Waveform` never pre-truncates), so only the
    /// leading `node_order.len()` entries of each are read as node voltages; `branch_currents`
    /// names which further entries are worth keeping.
    pub fn from_waveform(
        node_order: &[String],
        t: &[f64],
        x: &[Vec<f64>],
        branch_currents: &[(String, usize)],
    ) -> Self {
        let points = t
            .iter()
            .zip(x)
            .map(|(&time, row)| {
                (
                    time,
                    combined_values(node_order.len(), row, branch_currents),
                )
            })
            .collect();
        Self {
            node_order: combined_node_order(node_order, branch_currents),
            points,
        }
    }

    /// Parse a transient `.golden` file's text (this module's doc comment shows the format): a
    /// `@tran <node> ...` header line, then one `<time> <node value> ...` row per sample.
    ///
    /// # Errors
    ///
    /// [`HarnessError::Golden`] on a missing/malformed header (including a missing `@tran`
    /// marker — this is how [`GoldenTran::parse`] tells its own files apart from
    /// [`GoldenSweep`]'s), or a row whose value count doesn't match the header's node count.
    pub fn parse(text: &str) -> Result<Self, HarnessError> {
        let golden_err = |line: usize, message: &str| HarnessError::Golden {
            line,
            message: message.to_string(),
        };
        let mut real_lines = text
            .lines()
            .enumerate()
            .filter(|(_, raw)| {
                let t = raw.trim();
                !t.is_empty() && !t.starts_with('#')
            })
            .map(|(i, raw)| (i + 1, raw));

        let (header_line, header) = real_lines
            .next()
            .ok_or_else(|| golden_err(1, "empty tran golden file (expected a `@tran` header)"))?;
        let mut header_toks = header.split_whitespace();
        match header_toks.next() {
            Some("@tran") => {}
            _ => return Err(golden_err(header_line, "expected a `@tran` header marker")),
        }
        let node_order: Vec<String> = header_toks.map(str::to_string).collect();
        if node_order.is_empty() {
            return Err(golden_err(header_line, "header names no nodes"));
        }

        let mut points = Vec::new();
        for (line, raw) in real_lines {
            let toks: Vec<f64> = raw
                .split_whitespace()
                .map(|t| t.parse().map_err(|_| golden_err(line, "unparseable value")))
                .collect::<Result<_, _>>()?;
            if toks.len() != node_order.len() + 1 {
                return Err(golden_err(
                    line,
                    &format!(
                        "expected {} value(s) (1 time + {} node), found {}",
                        node_order.len() + 1,
                        node_order.len(),
                        toks.len()
                    ),
                ));
            }
            points.push((toks[0], toks[1..].to_vec()));
        }
        Ok(Self { node_order, points })
    }

    /// Read a transient `.golden` file from disk.
    ///
    /// # Errors
    ///
    /// [`HarnessError::MissingGolden`] if `path` doesn't exist/can't be read;
    /// [`HarnessError::Golden`] if its contents don't parse.
    pub fn read(path: &std::path::Path) -> Result<Self, HarnessError> {
        let text = std::fs::read_to_string(path)
            .map_err(|_| HarnessError::MissingGolden(path.display().to_string()))?;
        Self::parse(&text)
    }

    /// Render as transient `.golden` text — round-trips exactly through [`Self::parse`].
    pub fn render(&self) -> String {
        let mut out = format!("@tran {}\n", self.node_order.join(" "));
        for (time, values) in &self.points {
            out.push_str(&time.to_string());
            for v in values {
                out.push(' ');
                out.push_str(&v.to_string());
            }
            out.push('\n');
        }
        out
    }
}

/// One committed golden reference for an `.ac` small-signal sweep (T5): every swept frequency's
/// own complex node voltages and branch currents, in frequency order.
///
/// Same table shape as [`GoldenTran`] (frequency in place of time) but with a complex value per
/// name rather than a real one, and an `@ac` header marker so a `.golden` file's own text says
/// unambiguously which parser it needs.
#[derive(Clone, Debug, PartialEq)]
pub struct GoldenAc {
    /// Node names (and `I(<device>)` branch-current labels), in the same order as each point's
    /// values.
    pub node_order: Vec<String>,
    /// `(frequency, complex values as `(re, im)` in `node_order`)`, in frequency order.
    pub points: Vec<(f64, Vec<(f64, f64)>)>,
}

impl GoldenAc {
    /// Build from a solved AC sweep's node names, frequency points, complex solution rows, and
    /// named branch currents (§ this module's own doc comment). Each row of `x` is the full
    /// complex solution vector (`va_acnoise::ac::AcResponse::x`'s own shape), so only the leading
    /// `node_order.len()` entries are node voltages; `branch_currents` names which further
    /// entries are worth keeping.
    pub fn from_response(
        node_order: &[String],
        f: &[f64],
        x: &[Vec<(f64, f64)>],
        branch_currents: &[(String, usize)],
    ) -> Self {
        let points = f
            .iter()
            .zip(x)
            .map(|(&freq, row)| {
                let mut values = row[..node_order.len()].to_vec();
                values.extend(branch_currents.iter().map(|&(_, idx)| row[idx]));
                (freq, values)
            })
            .collect();
        Self {
            node_order: combined_node_order(node_order, branch_currents),
            points,
        }
    }

    /// Parse an AC `.golden` file's text (this module's doc comment shows the format): an
    /// `@ac <name> ...` header line, then one `<frequency> <re> <im> ...` row per point, with
    /// **two** values per header name.
    ///
    /// # Errors
    ///
    /// [`HarnessError::Golden`] on a missing/malformed header (including a missing `@ac`
    /// marker — this is how [`GoldenAc::parse`] tells its own files apart from [`GoldenTran`]'s
    /// and [`GoldenSweep`]'s), or a row whose value count isn't `1 + 2 × names`.
    pub fn parse(text: &str) -> Result<Self, HarnessError> {
        let golden_err = |line: usize, message: &str| HarnessError::Golden {
            line,
            message: message.to_string(),
        };
        let mut real_lines = text
            .lines()
            .enumerate()
            .filter(|(_, raw)| {
                let t = raw.trim();
                !t.is_empty() && !t.starts_with('#')
            })
            .map(|(i, raw)| (i + 1, raw));

        let (header_line, header) = real_lines
            .next()
            .ok_or_else(|| golden_err(1, "empty ac golden file (expected an `@ac` header)"))?;
        let mut header_toks = header.split_whitespace();
        match header_toks.next() {
            Some("@ac") => {}
            _ => return Err(golden_err(header_line, "expected an `@ac` header marker")),
        }
        let node_order: Vec<String> = header_toks.map(str::to_string).collect();
        if node_order.is_empty() {
            return Err(golden_err(header_line, "header names no nodes"));
        }

        let mut points = Vec::new();
        for (line, raw) in real_lines {
            let toks: Vec<f64> = raw
                .split_whitespace()
                .map(|t| t.parse().map_err(|_| golden_err(line, "unparseable value")))
                .collect::<Result<_, _>>()?;
            if toks.len() != 2 * node_order.len() + 1 {
                return Err(golden_err(
                    line,
                    &format!(
                        "expected {} value(s) (1 frequency + {} × re/im), found {}",
                        2 * node_order.len() + 1,
                        node_order.len(),
                        toks.len()
                    ),
                ));
            }
            let values = toks[1..]
                .chunks_exact(2)
                .map(|c| (c[0], c[1]))
                .collect::<Vec<_>>();
            points.push((toks[0], values));
        }
        Ok(Self { node_order, points })
    }

    /// Read an AC `.golden` file from disk.
    ///
    /// # Errors
    ///
    /// [`HarnessError::MissingGolden`] if `path` doesn't exist/can't be read;
    /// [`HarnessError::Golden`] if its contents don't parse.
    pub fn read(path: &std::path::Path) -> Result<Self, HarnessError> {
        let text = std::fs::read_to_string(path)
            .map_err(|_| HarnessError::MissingGolden(path.display().to_string()))?;
        Self::parse(&text)
    }

    /// Render as AC `.golden` text — round-trips exactly through [`Self::parse`].
    pub fn render(&self) -> String {
        let mut out = format!("@ac {}\n", self.node_order.join(" "));
        for (freq, values) in &self.points {
            out.push_str(&freq.to_string());
            for (re, im) in values {
                out.push(' ');
                out.push_str(&re.to_string());
                out.push(' ');
                out.push_str(&im.to_string());
            }
            out.push('\n');
        }
        out
    }
}

/// One committed golden reference for a `.noise` sweep (T5.2): the output noise PSD at every
/// swept frequency.
///
/// Unlike every other golden type this module defines, there is no `node_order` — a noise
/// analysis probes a *single* output and produces a single number per frequency, so the probed
/// node's name is one field rather than a column list.
#[derive(Clone, Debug, PartialEq)]
pub struct GoldenNoise {
    /// The probed output node's name (`va_netlist::NoiseCard::output`).
    pub output: String,
    /// The input source the second column is referred back to (`va_netlist::NoiseCard::source`).
    pub source: String,
    /// `(frequency, output PSD, input-referred PSD)` in V²/Hz, in frequency order.
    pub points: Vec<(f64, f64, f64)>,
}

impl GoldenNoise {
    /// Build from a solved spectrum, the node it was probed at, and the source it is referred to.
    ///
    /// `input_psd` may be shorter than `psd` (it is empty when no input source was resolved), in
    /// which case the missing entries record `0.0` — a golden file always carries both columns,
    /// so a row's shape never depends on which questions a particular run happened to ask.
    pub fn from_spectrum(
        output: &str,
        source: &str,
        f: &[f64],
        psd: &[f64],
        input_psd: &[f64],
    ) -> Self {
        Self {
            output: output.to_string(),
            source: source.to_string(),
            points: f
                .iter()
                .zip(psd)
                .enumerate()
                .map(|(i, (&freq, &p))| (freq, p, input_psd.get(i).copied().unwrap_or(0.0)))
                .collect(),
        }
    }

    /// Parse a noise `.golden` file's text (this module's doc comment shows the format): a
    /// `@noise <output>` header line, then one `<frequency> <psd>` row per point.
    ///
    /// # Errors
    ///
    /// [`HarnessError::Golden`] on a missing/malformed header (including a missing `@noise`
    /// marker, which is how this tells its own files apart from [`GoldenAc`]'s and
    /// [`GoldenTran`]'s), or a row that isn't exactly two values.
    pub fn parse(text: &str) -> Result<Self, HarnessError> {
        let golden_err = |line: usize, message: &str| HarnessError::Golden {
            line,
            message: message.to_string(),
        };
        let mut real_lines = text
            .lines()
            .enumerate()
            .filter(|(_, raw)| {
                let t = raw.trim();
                !t.is_empty() && !t.starts_with('#')
            })
            .map(|(i, raw)| (i + 1, raw));

        let (header_line, header) = real_lines
            .next()
            .ok_or_else(|| golden_err(1, "empty noise golden file (expected a `@noise` header)"))?;
        let mut header_toks = header.split_whitespace();
        match header_toks.next() {
            Some("@noise") => {}
            _ => return Err(golden_err(header_line, "expected a `@noise` header marker")),
        }
        let output = header_toks
            .next()
            .ok_or_else(|| golden_err(header_line, "header names no output node"))?
            .to_string();
        let source = header_toks
            .next()
            .ok_or_else(|| golden_err(header_line, "header names no input source"))?
            .to_string();

        let mut points = Vec::new();
        for (line, raw) in real_lines {
            let toks: Vec<f64> = raw
                .split_whitespace()
                .map(|t| t.parse().map_err(|_| golden_err(line, "unparseable value")))
                .collect::<Result<_, _>>()?;
            match toks.as_slice() {
                [f, psd, input] => points.push((*f, *psd, *input)),
                other => {
                    return Err(golden_err(
                        line,
                        &format!(
                        "expected 3 values (frequency + output PSD + input-referred PSD), found {}",
                        other.len()
                    ),
                    ))
                }
            }
        }
        Ok(Self {
            output,
            source,
            points,
        })
    }

    /// Read a noise `.golden` file from disk.
    ///
    /// # Errors
    ///
    /// [`HarnessError::MissingGolden`] if `path` doesn't exist/can't be read;
    /// [`HarnessError::Golden`] if its contents don't parse.
    pub fn read(path: &std::path::Path) -> Result<Self, HarnessError> {
        let text = std::fs::read_to_string(path)
            .map_err(|_| HarnessError::MissingGolden(path.display().to_string()))?;
        Self::parse(&text)
    }

    /// Render as noise `.golden` text — round-trips exactly through [`Self::parse`].
    pub fn render(&self) -> String {
        let mut out = format!("@noise {} {}\n", self.output, self.source);
        for (f, psd, input) in &self.points {
            out.push_str(&format!("{f} {psd} {input}\n"));
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn noise_parse_reads_the_noise_marker_and_rows() {
        let g = GoldenNoise::parse(
            "# c\n@noise a V1\n10 1.98771e-18 4.97535e-17\n100 1.9e-18 4.7e-17\n",
        )
        .unwrap();
        assert_eq!(g.output, "a");
        assert_eq!(g.source, "V1");
        assert_eq!(
            g.points,
            vec![(10.0, 1.98771e-18, 4.97535e-17), (100.0, 1.9e-18, 4.7e-17)]
        );
    }

    #[test]
    fn noise_parse_requires_the_noise_marker() {
        assert!(GoldenNoise::parse("@ac a\n10 1e-18 0\n").is_err());
        assert!(GoldenNoise::parse("@tran a\n10 1e-18\n").is_err());
    }

    #[test]
    fn noise_parse_requires_an_input_source_in_the_header() {
        // The pre-input-referral header named only the output. Accepting it would leave
        // `source` unset while the rows still carry two value columns — reject instead.
        assert!(GoldenNoise::parse("@noise a\n10 1e-18 5e-17\n").is_err());
    }

    #[test]
    fn noise_row_with_wrong_value_count_is_an_error() {
        assert!(GoldenNoise::parse("@noise a V1\n10\n").is_err());
        // Two values is the *old* row shape — it must not silently parse as output-only.
        assert!(GoldenNoise::parse("@noise a V1\n10 1e-18\n").is_err());
        assert!(GoldenNoise::parse("@noise a V1\n10 1e-18 5e-17 9\n").is_err());
    }

    #[test]
    fn noise_render_round_trips_through_parse() {
        let g = GoldenNoise {
            output: "a".to_string(),
            source: "V1".to_string(),
            points: vec![
                (10.0, 1.987_747_2e-18, 4.975_307e-17),
                (1e7, 1.987_747_2e-18, 4.975_307e-17),
            ],
        };
        assert_eq!(GoldenNoise::parse(&g.render()).unwrap(), g);
    }

    #[test]
    fn parse_ignores_comments_and_blank_lines() {
        let g = GoldenDc::parse("# a comment\n\nin 1\nmid 0.5\n").unwrap();
        assert_eq!(g.node_order, vec!["in", "mid"]);
        assert_eq!(g.values, vec![1.0, 0.5]);
    }

    #[test]
    fn render_round_trips_through_parse() {
        let g = GoldenDc {
            node_order: vec!["in".to_string(), "mid".to_string()],
            values: vec![1.0, 0.123456789012345],
        };
        let text = g.render();
        let parsed = GoldenDc::parse(&text).unwrap();
        assert_eq!(g, parsed);
    }

    #[test]
    fn missing_value_is_an_error() {
        assert!(GoldenDc::parse("in\n").is_err());
    }

    #[test]
    fn unparseable_value_is_an_error() {
        assert!(GoldenDc::parse("in notanumber\n").is_err());
    }

    #[test]
    fn extra_tokens_are_an_error() {
        assert!(GoldenDc::parse("in 1 extra\n").is_err());
    }

    #[test]
    fn from_operating_point_drops_trailing_branch_unknowns_when_not_named() {
        // `x` carries a source's own branch-current unknown after the node voltages, but with no
        // `branch_currents` entries naming it, it's dropped just like before this feature existed.
        let node_order = vec!["in".to_string(), "mid".to_string()];
        let x = [1.0, 0.5, -0.001];
        let g = GoldenDc::from_operating_point(&node_order, &x, &[]);
        assert_eq!(g.node_order, vec!["in", "mid"]);
        assert_eq!(g.values, vec![1.0, 0.5]);
    }

    #[test]
    fn from_operating_point_appends_named_branch_currents() {
        let node_order = vec!["in".to_string(), "mid".to_string()];
        let x = [1.0, 0.5, -0.0005];
        let g = GoldenDc::from_operating_point(&node_order, &x, &[("V1".to_string(), 2)]);
        assert_eq!(g.node_order, vec!["in", "mid", "I(V1)"]);
        assert_eq!(g.values, vec![1.0, 0.5, -0.0005]);
    }

    #[test]
    fn sweep_parse_reads_header_and_rows() {
        let g = GoldenSweep::parse("# a comment\nV1 in\n0 0\n0.1 0.1\n").unwrap();
        assert_eq!(g.source, "V1");
        assert_eq!(g.node_order, vec!["in"]);
        assert_eq!(g.points, vec![(0.0, vec![0.0]), (0.1, vec![0.1])]);
    }

    #[test]
    fn sweep_render_round_trips_through_parse() {
        let g = GoldenSweep {
            source: "V1".to_string(),
            node_order: vec!["in".to_string()],
            points: vec![(0.0, vec![0.0]), (0.3, vec![-1.095908e-9])],
        };
        let text = g.render();
        let parsed = GoldenSweep::parse(&text).unwrap();
        assert_eq!(g, parsed);
    }

    #[test]
    fn sweep_empty_file_is_an_error() {
        assert!(GoldenSweep::parse("").is_err());
        assert!(GoldenSweep::parse("# only a comment\n").is_err());
    }

    #[test]
    fn sweep_row_with_wrong_value_count_is_an_error() {
        // Header declares one node ("in"), so each row needs exactly 2 values (swept + in).
        assert!(GoldenSweep::parse("V1 in\n0 0 1\n").is_err());
        assert!(GoldenSweep::parse("V1 in\n0\n").is_err());
    }

    #[test]
    fn sweep_from_sweep_matches_manual_construction() {
        let g = GoldenSweep::from_sweep(
            "V1",
            &["in".to_string()],
            &[(0.0, vec![0.0]), (0.1, vec![0.1])],
            &[],
        );
        assert_eq!(g.source, "V1");
        assert_eq!(g.node_order, vec!["in"]);
        assert_eq!(g.points, vec![(0.0, vec![0.0]), (0.1, vec![0.1])]);
    }

    #[test]
    fn sweep_from_sweep_appends_named_branch_currents() {
        let g = GoldenSweep::from_sweep(
            "V1",
            &["in".to_string()],
            &[(0.0, vec![0.0, -1e-9]), (0.1, vec![0.1, -2e-9])],
            &[("V1".to_string(), 1)],
        );
        assert_eq!(g.node_order, vec!["in", "I(V1)"]);
        assert_eq!(
            g.points,
            vec![(0.0, vec![0.0, -1e-9]), (0.1, vec![0.1, -2e-9])]
        );
    }

    #[test]
    fn tran_parse_reads_the_tran_marker_and_rows() {
        let g = GoldenTran::parse("# a comment\n@tran out\n0 0\n2e-5 0.0995\n").unwrap();
        assert_eq!(g.node_order, vec!["out"]);
        assert_eq!(g.points, vec![(0.0, vec![0.0]), (2e-5, vec![0.0995])]);
    }

    #[test]
    fn tran_parse_requires_the_tran_marker() {
        // Without `@tran`, this is indistinguishable from a `GoldenSweep` header — must error,
        // not silently misparse the source name as a node.
        assert!(GoldenTran::parse("V1 in\n0 0\n").is_err());
    }

    #[test]
    fn tran_render_round_trips_through_parse() {
        let g = GoldenTran {
            node_order: vec!["out".to_string()],
            points: vec![(0.0, vec![0.0]), (1e-3, vec![3.160603e0])],
        };
        let text = g.render();
        let parsed = GoldenTran::parse(&text).unwrap();
        assert_eq!(g, parsed);
    }

    #[test]
    fn tran_row_with_wrong_value_count_is_an_error() {
        assert!(GoldenTran::parse("@tran out\n0 0 1\n").is_err());
        assert!(GoldenTran::parse("@tran out\n0\n").is_err());
    }

    #[test]
    fn tran_from_waveform_drops_trailing_branch_unknowns_when_not_named() {
        let node_order = vec!["in".to_string(), "out".to_string()];
        let t = [0.0, 1e-3];
        let x = vec![vec![5.0, 0.0, -0.005], vec![5.0, 3.160603, -0.0018]];
        let g = GoldenTran::from_waveform(&node_order, &t, &x, &[]);
        assert_eq!(g.node_order, vec!["in", "out"]);
        assert_eq!(
            g.points,
            vec![(0.0, vec![5.0, 0.0]), (1e-3, vec![5.0, 3.160603])]
        );
    }

    #[test]
    fn ac_parse_reads_the_ac_marker_and_complex_rows() {
        let g =
            GoldenAc::parse("# a comment\n@ac out I(V1)\n1 0.99 -0.006 -3.9e-8 -6.2e-6\n").unwrap();
        assert_eq!(g.node_order, vec!["out", "I(V1)"]);
        assert_eq!(
            g.points,
            vec![(1.0, vec![(0.99, -0.006), (-3.9e-8, -6.2e-6)])]
        );
    }

    #[test]
    fn ac_parse_requires_the_ac_marker() {
        // Without `@ac`, this is indistinguishable from a `GoldenTran`/`GoldenSweep` header.
        assert!(GoldenAc::parse("@tran out\n1 0.99 -0.006\n").is_err());
        assert!(GoldenAc::parse("V1 in\n0 0\n").is_err());
    }

    #[test]
    fn ac_row_with_wrong_value_count_is_an_error() {
        // One name needs exactly 3 values per row (frequency + re + im) — an odd count is
        // exactly the shape a real/imaginary pair silently going missing would produce.
        assert!(GoldenAc::parse("@ac out\n1 0.99\n").is_err());
        assert!(GoldenAc::parse("@ac out\n1 0.99 -0.006 5\n").is_err());
    }

    #[test]
    fn ac_render_round_trips_through_parse() {
        let g = GoldenAc {
            node_order: vec!["out".to_string(), "I(V1)".to_string()],
            points: vec![
                (
                    1.0,
                    vec![(0.999960562, -0.00628294), (-3.94769e-8, -6.28294e-6)],
                ),
                (1e6, vec![(2.53303e-8, -1.59155e-4), (-1e-3, -1.59155e-7)]),
            ],
        };
        let parsed = GoldenAc::parse(&g.render()).unwrap();
        assert_eq!(g, parsed);
    }

    #[test]
    fn ac_from_response_appends_named_branch_currents() {
        let node_order = vec!["in".to_string(), "out".to_string()];
        let f = [1.0];
        // Full complex solution row: two nodes, then the source's own branch-current unknown.
        let x = vec![vec![(1.0, 0.0), (0.99, -0.006), (-3.9e-8, -6.2e-6)]];
        let g = GoldenAc::from_response(&node_order, &f, &x, &[("V1".to_string(), 2)]);
        assert_eq!(g.node_order, vec!["in", "out", "I(V1)"]);
        assert_eq!(
            g.points,
            vec![(1.0, vec![(1.0, 0.0), (0.99, -0.006), (-3.9e-8, -6.2e-6)])]
        );

        // With no branch currents named, the trailing unknown is dropped, same as every other
        // golden constructor.
        let g = GoldenAc::from_response(&node_order, &f, &x, &[]);
        assert_eq!(g.node_order, vec!["in", "out"]);
        assert_eq!(g.points[0].1.len(), 2);
    }

    #[test]
    fn tran_from_waveform_appends_named_branch_currents() {
        let node_order = vec!["in".to_string(), "out".to_string()];
        let t = [0.0, 1e-3];
        let x = vec![vec![5.0, 0.0, -0.005], vec![5.0, 3.160603, -0.0018]];
        let g = GoldenTran::from_waveform(&node_order, &t, &x, &[("V1".to_string(), 2)]);
        assert_eq!(g.node_order, vec!["in", "out", "I(V1)"]);
        assert_eq!(
            g.points,
            vec![
                (0.0, vec![5.0, 0.0, -0.005]),
                (1e-3, vec![5.0, 3.160603, -0.0018])
            ]
        );
    }
}
