//! Golden reference file format for a DC operating point (§ ladder rungs 1/5 — the
//! "single operating point" case). A `.dc` sweep or transient waveform isn't wired to golden
//! yet — see `docs/roadmap.md`'s T6.3 notes.
//!
//! A `.golden` file is plain text: one `<node> <value>` pair per line, in the circuit's own
//! `node_order` (so a byte diff against a regenerated file reads as a real circuit change, not
//! reordering noise). Blank lines and `#`-prefixed comment lines are ignored.
//!
//! ```text
//! # golden/divider.golden — generated by `cargo xtask gen-golden`
//! in 1
//! mid 0.5
//! ```

use crate::HarnessError;

/// One committed golden reference: a DC operating point's node voltages, in `node_order`.
#[derive(Clone, Debug, PartialEq)]
pub struct GoldenDc {
    /// Node names, in the same order as [`Self::values`].
    pub node_order: Vec<String>,
    /// Node voltages, one per `node_order` entry.
    pub values: Vec<f64>,
}

impl GoldenDc {
    /// Build from a solved circuit's node names and full unknown vector — only the leading
    /// `node_order.len()` entries of `x` are node voltages (branch-current/internal unknowns,
    /// if any, follow them — see `va-cli::build_instances`'s doc comment), so this only ever
    /// reads that prefix.
    pub fn from_operating_point(node_order: &[String], x: &[f64]) -> Self {
        Self {
            node_order: node_order.to_vec(),
            values: x[..node_order.len()].to_vec(),
        }
    }

    /// Parse a `.golden` file's text (this module's doc comment shows the format).
    ///
    /// # Errors
    ///
    /// [`HarnessError::Golden`] on a line that isn't blank/a comment/`<node> <value>`.
    pub fn parse(text: &str) -> Result<Self, HarnessError> {
        let mut node_order = Vec::new();
        let mut values = Vec::new();
        for (i, raw) in text.lines().enumerate() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let golden_err = |message: &str| HarnessError::Golden {
                line: i + 1,
                message: message.to_string(),
            };
            let mut parts = line.split_whitespace();
            let name = parts
                .next()
                .ok_or_else(|| golden_err("expected `<node> <value>`"))?;
            let value: f64 = parts
                .next()
                .ok_or_else(|| golden_err("missing value"))?
                .parse()
                .map_err(|_| golden_err("unparseable value"))?;
            if parts.next().is_some() {
                return Err(golden_err(
                    "expected exactly `<node> <value>`, found extra tokens",
                ));
            }
            node_order.push(name.to_string());
            values.push(value);
        }
        Ok(Self { node_order, values })
    }

    /// Read a `.golden` file from disk.
    ///
    /// # Errors
    ///
    /// [`HarnessError::MissingGolden`] if `path` doesn't exist/can't be read;
    /// [`HarnessError::Golden`] if its contents don't parse.
    pub fn read(path: &std::path::Path) -> Result<Self, HarnessError> {
        let text = std::fs::read_to_string(path)
            .map_err(|_| HarnessError::MissingGolden(path.display().to_string()))?;
        Self::parse(&text)
    }

    /// Render as `.golden` text — round-trips exactly through [`Self::parse`], since `f64`'s
    /// `Display` is Rust's shortest-round-trippable-decimal formatting, not a truncated one.
    pub fn render(&self) -> String {
        let mut out = String::new();
        for (name, value) in self.node_order.iter().zip(&self.values) {
            out.push_str(&format!("{name} {value}\n"));
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_ignores_comments_and_blank_lines() {
        let g = GoldenDc::parse("# a comment\n\nin 1\nmid 0.5\n").unwrap();
        assert_eq!(g.node_order, vec!["in", "mid"]);
        assert_eq!(g.values, vec![1.0, 0.5]);
    }

    #[test]
    fn render_round_trips_through_parse() {
        let g = GoldenDc {
            node_order: vec!["in".to_string(), "mid".to_string()],
            values: vec![1.0, 0.123456789012345],
        };
        let text = g.render();
        let parsed = GoldenDc::parse(&text).unwrap();
        assert_eq!(g, parsed);
    }

    #[test]
    fn missing_value_is_an_error() {
        assert!(GoldenDc::parse("in\n").is_err());
    }

    #[test]
    fn unparseable_value_is_an_error() {
        assert!(GoldenDc::parse("in notanumber\n").is_err());
    }

    #[test]
    fn extra_tokens_are_an_error() {
        assert!(GoldenDc::parse("in 1 extra\n").is_err());
    }

    #[test]
    fn from_operating_point_drops_trailing_branch_unknowns() {
        // `x` carries a source's own branch-current unknown after the node voltages.
        let node_order = vec!["in".to_string(), "mid".to_string()];
        let x = [1.0, 0.5, -0.001];
        let g = GoldenDc::from_operating_point(&node_order, &x);
        assert_eq!(g.values, vec![1.0, 0.5]);
    }
}
